#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

TXT='links.txt'
REGEX='^https://git(hub|lab)\.com/'
GIT='git'

[[ ! -z "$1"   ]] && TXT="$1"
[[ ! -z "$2"   ]] && GIT="$2"
[[ ! -e "$TXT" ]] && exit 1

awk '{print $2}' "$TXT"  \
  | grep -E "$REGEX"     \
  | cut -d/ -f -5        \
  | sort -u              \
  | while read -r URL
    do
      grep "$URL" "$TXT" | while read -r _ _ T
      do
        TAG="${T//+/}"
        [[ -z "$TAG" ]] && continue
        REPO="$(echo "$URL" | rev | cut -d/ -f1 | rev)"
        DIR="${GIT}/${TAG//+/}/$REPO"
        printf "%-72s %s\\n" "$DIR" "$URL"
      done
    done | sort
