#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

BIN="$(basename "$0")"
RED="$(tput setaf 196)"
NORMAL="$(tput sgr0)"
GIT='git'
REGEX='^https://git(hub|lab)\.com/'
TXT='links.txt'

die ()
{
  printf "%s\\n" "${RED}[ERROR] $1 $NORMAL" && usage && exit 1
}

function usage()
{
cat << EOF

Usage:

\`\`\`bash

  $BIN [LINKS_FILE] [GIT_DIR] [REGEX]

\`\`\`

Extract _github_ and _gitlab_ urls from \`links.txt\` using tags to
group in directories and generate \`.git-repos\` output format.

Example:

\`\`\`bash

  cat links.txt

    2020-09-27 https://github.com/muesli/duf +tty
    2020-09-27 https://shaunlebron.github.io/pacman-mazegen/ +game
    2020-09-28 https://github.com/hlissner/doom-emacs +emacs
    2020-09-28 https://github.com/shoumikchow/bbox-visualizer +viz
    2020-09-30 https://github.com/mytechnotalent/Python-For-Kids +python
    2020-09-30 https://github.com/tridactyl/tridactyl +vim
    2020-09-30 https://mosermichael.github.io/duckduckbang/html/main.html +http
    2020-10-01 https://github.com/koutto/hardware-hacking/blob/master/Hardware-Hacking-Experiments-Jeremy-Brun-Nouvion-2020.pdf +hack
    2020-10-01 https://github.com/rbanffy/3270font +font
    2020-10-02 https://google.github.io/styleguide/shellguide.html +bash

  $BIN links.txt

    git/emacs/doom-emacs        https://github.com/hlissner/doom-emacs
    git/font/3270font           https://github.com/rbanffy/3270font
    git/hack/hardware-hacking   https://github.com/koutto/hardware-hacking
    git/python/Python-For-Kids  https://github.com/mytechnotalent/Python-For-Kids
    git/tty/duf                 https://github.com/muesli/duf
    git/vim/tridactyl           https://github.com/tridactyl/tridactyl
    git/viz/bbox-visualizer     https://github.com/shoumikchow/bbox-visualizer

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1"   ]] || TXT="$1"
[[ -z "$2"   ]] || GIT="$2"
[[ -z "$3"   ]] || REGEX="$3"
[[ -e "$TXT" ]] || die "NOT FOUND FILE: $TXT"

awk '{print $2}' "$TXT"  \
  | grep -E "$REGEX"     \
  | cut -d/ -f -5        \
  | sort -u              \
  | while read -r URL
    do
      grep "$URL" "$TXT" | while read -r _ _ T
      do
        TAG="${T//+/}"
        [[ -z "$TAG" ]] && continue
        REPO="$(echo "$URL" | rev | cut -d/ -f1 | rev)"
        DIR="${GIT}/${TAG//+/}/$REPO"
        printf "%-72s %s\\n" "$DIR" "$URL"
      done
    done | sort -u
